#!/usr/bin/env bash
# Copyright 2026 Aleksey Martynov and contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

export HADOOP_CONF_DIR=/opt/hadoop/etc/hadoop
export KRB5_CONFIG=/shared/krb5.conf
export HADOOP_OPTS="${HADOOP_OPTS:-} -Djava.security.krb5.conf=/shared/krb5.conf"

until test -r /shared/nn-hdfs.test.local.keytab; do
  sleep 2
done

mkdir -p /data/name /data/data
if ! test -d /data/name/current; then
  hdfs namenode -format -force -nonInteractive
fi

hdfs --daemon start namenode
hdfs --daemon start datanode

trap 'hdfs --daemon stop datanode; hdfs --daemon stop namenode' TERM INT
tail -F /opt/hadoop/logs/*
