{{- if .Values.tls.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kudos.fullname" . }}-vault-agent
  labels:
    {{- include "kudos.labels" . | nindent 4 }}
data:
  agent.hcl: |-
{{ .Files.Get "files/agent.hcl" | indent 4 }}
{{- end }}
